# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='New',
        ),
    ]
