# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0002_auto_20170914_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='content',
        ),
        migrations.AddField(
            model_name='new',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='new',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
