# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0003_auto_20170914_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='name',
        ),
    ]
