# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0004_remove_new_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='id',
        ),
        migrations.AddField(
            model_name='new',
            name='unique_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
