# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-15 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0006_auto_20170915_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_link',
            field=models.TextField(null=True),
        ),
    ]
